#!/bin/sh

ENABLED=yes
PROCS=msd_lite
ARGS="-d -c /opt/etc/msd_lite.conf"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# check and remove stale pid
if ! pidof $PROCS 1>/dev/null 2>&1; then
    rm -f /opt/var/run/$PROCS.pid
fi

. /opt/etc/init.d/rc.func
